"! <p class="shorttext synchronized" lang="en">Generated by SADL Generation Toolkit</p>
CLASS zcl_ztt_c_tasks DEFINITION
  PUBLIC
  INHERITING FROM cl_sadl_gtk_exposure_mpc
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.
    METHODS get_paths
        REDEFINITION.
    METHODS get_timestamp
        REDEFINITION.

  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_ztt_c_tasks IMPLEMENTATION.


  METHOD get_paths.
    et_paths = VALUE #( ( `CDS~ZTT_C_TASKS` ) ).
  ENDMETHOD.


  METHOD get_timestamp.
    rv_timestamp = 20200702165811.
  ENDMETHOD.


ENDCLASS.
