"! <p class="shorttext synchronized" lang="en">Generated Constants Interface</p>
INTERFACE zif_tt_i_tasks_c
  PUBLIC .


  INTERFACES /bobf/if_lib_constants .

  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Actions</p>
    BEGIN OF sc_action,
      BEGIN OF ztt_i_tasks,
        create_tr_cu         TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF78D636AE37442',
        create_tr_wb         TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF78D636AE35442',
        create_ztt_i_tasks   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF65901B032B3C9',
        delete_ztt_i_tasks   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF65901B03333C9',
        lock_ztt_i_tasks     TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF65901B031F3C9',
        save_ztt_i_tasks     TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF65901B033B3C9',
        unlock_ztt_i_tasks   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF65901B03233C9',
        update_ztt_i_tasks   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF65901B032F3C9',
        validate_ztt_i_tasks TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF65901B03373C9',
      END OF ztt_i_tasks,
      BEGIN OF ztt_i_task_comments,
        create_ztt_i_task_comments   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF66F0E66A153D1',
        delete_ztt_i_task_comments   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF66F0E66A1D3D1',
        save_ztt_i_task_comments     TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF66F0E66A253D1',
        update_ztt_i_task_comments   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF66F0E66A193D1',
        validate_ztt_i_task_comments TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF66F0E66A213D1',
      END OF ztt_i_task_comments,
      BEGIN OF ztt_i_task_time_log,
        create_ztt_i_task_time_log   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF6611C0E51F3CB',
        delete_ztt_i_task_time_log   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF6611C0E5273CB',
        save_ztt_i_task_time_log     TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF6611C0E52F3CB',
        update_ztt_i_task_time_log   TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF6611C0E5233CB',
        validate_ztt_i_task_time_log TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF6611C0E52B3CB',
      END OF ztt_i_task_time_log,
      BEGIN OF ztt_i_task_transport_request,
        create_ztt_i_task_transport_re TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF67E42345FD3DA',
        delete_ztt_i_task_transport_re TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF67E42346053DA',
        save_ztt_i_task_transport_requ TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF67E423460D3DA',
        update_ztt_i_task_transport_re TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF67E42346013DA',
        validate_ztt_i_task_transport_ TYPE /bobf/act_key VALUE '0250E0674B721EEAAEF67E42346093DA',
      END OF ztt_i_task_transport_request,
    END OF sc_action .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Action Parameter Attributes</p>
    BEGIN OF sc_action_attribute,
      BEGIN OF ztt_i_tasks,
        BEGIN OF lock_ztt_i_tasks,
          generic               TYPE string VALUE 'GENERIC',
          edit_mode             TYPE string VALUE 'EDIT_MODE',
          all_none              TYPE string VALUE 'ALL_NONE',
          scope                 TYPE string VALUE 'SCOPE',
          force_invalidation    TYPE string VALUE 'FORCE_INVALIDATION',
          lock_parameter_buffer TYPE string VALUE 'LOCK_PARAMETER_BUFFER',
        END OF lock_ztt_i_tasks,
        BEGIN OF unlock_ztt_i_tasks,
          generic               TYPE string VALUE 'GENERIC',
          edit_mode             TYPE string VALUE 'EDIT_MODE',
          all_none              TYPE string VALUE 'ALL_NONE',
          scope                 TYPE string VALUE 'SCOPE',
          force_invalidation    TYPE string VALUE 'FORCE_INVALIDATION',
          lock_parameter_buffer TYPE string VALUE 'LOCK_PARAMETER_BUFFER',
        END OF unlock_ztt_i_tasks,
      END OF ztt_i_tasks,
    END OF sc_action_attribute .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Alternative Keys</p>
    BEGIN OF sc_alternative_key,
      BEGIN OF ztt_i_tasks,
        db_key       TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF65901B03493C9',
        project_code TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF7093300351410',
      END OF ztt_i_tasks,
      BEGIN OF ztt_i_task_comments,
        db_key     TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF66F0E669BD3D1',
        parent_key TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF66F0E669BF3D1',
      END OF ztt_i_task_comments,
      BEGIN OF ztt_i_task_time_log,
        db_key     TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF6611C0E4BB3CB',
        parent_key TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF6611C0E4BD3CB',
      END OF ztt_i_task_time_log,
      BEGIN OF ztt_i_task_transport_request,
        db_key     TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF67E423459F3DA',
        parent_key TYPE /bobf/obm_altkey_key VALUE '0250E0674B721EEAAEF67E42345A13DA',
      END OF ztt_i_task_transport_request,
    END OF sc_alternative_key .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Associations</p>
    BEGIN OF sc_association,
      BEGIN OF ztt_i_tasks,
        lock               TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF65901B031D3C9',
        message            TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF65901B03193C9',
        property           TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF65901B03293C9',
        _comments          TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF66F0E66A093D1',
        _timelog           TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF6611C0E5133CB',
        _transportrequests TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF67E42345F13DA',
      END OF ztt_i_tasks,
      BEGIN OF ztt_i_tasks_lock,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF65901B03413C9',
      END OF ztt_i_tasks_lock,
      BEGIN OF ztt_i_tasks_message,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF65901B033F3C9',
      END OF ztt_i_tasks_message,
      BEGIN OF ztt_i_tasks_property,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF65901B03433C9',
      END OF ztt_i_tasks_property,
      BEGIN OF ztt_i_task_comments,
        message   TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF66F0E66A0F3D1',
        property  TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF66F0E66A133D1',
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF66F0E66A293D1',
        to_root   TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF66F0E66A2B3D1',
      END OF ztt_i_task_comments,
      BEGIN OF ztt_i_task_comments_message,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF66F0E66A2D3D1',
      END OF ztt_i_task_comments_message,
      BEGIN OF ztt_i_task_comments_property,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF66F0E66A2F3D1',
      END OF ztt_i_task_comments_property,
      BEGIN OF ztt_i_task_time_log,
        message   TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF6611C0E5193CB',
        property  TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF6611C0E51D3CB',
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF6611C0E5333CB',
        to_root   TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF6611C0E5353CB',
      END OF ztt_i_task_time_log,
      BEGIN OF ztt_i_task_time_log_message,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF6611C0E5373CB',
      END OF ztt_i_task_time_log_message,
      BEGIN OF ztt_i_task_time_log_property,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF6611C0E5393CB',
      END OF ztt_i_task_time_log_property,
      BEGIN OF ztt_i_task_transport_request,
        message   TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF67E42345F73DA',
        property  TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF67E42345FB3DA',
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF67E42346113DA',
        to_root   TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF67E42346133DA',
      END OF ztt_i_task_transport_request,
      BEGIN OF ztt_i_task_transport_request_m,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF67E42346153DA',
      END OF ztt_i_task_transport_request_m,
      BEGIN OF ztt_i_task_transport_request_p,
        to_parent TYPE /bobf/obm_assoc_key VALUE '0250E0674B721EEAAEF67E42346173DA',
      END OF ztt_i_task_transport_request_p,
    END OF sc_association .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Association Parameter Attributes</p>
    BEGIN OF sc_association_attribute,
      BEGIN OF ztt_i_tasks,
        BEGIN OF property,
          all_node_property              TYPE string VALUE 'ALL_NODE_PROPERTY',
          all_node_attribute_property    TYPE string VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
          all_association_property       TYPE string VALUE 'ALL_ASSOCIATION_PROPERTY',
          all_association_attribute_prop TYPE string VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
          all_action_property            TYPE string VALUE 'ALL_ACTION_PROPERTY',
          all_action_attribute_property  TYPE string VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
          all_query_property             TYPE string VALUE 'ALL_QUERY_PROPERTY',
          all_query_attribute_property   TYPE string VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
          all_subtree_property           TYPE string VALUE 'ALL_SUBTREE_PROPERTY',
        END OF property,
      END OF ztt_i_tasks,
      BEGIN OF ztt_i_task_comments,
        BEGIN OF property,
          all_node_property              TYPE string VALUE 'ALL_NODE_PROPERTY',
          all_node_attribute_property    TYPE string VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
          all_association_property       TYPE string VALUE 'ALL_ASSOCIATION_PROPERTY',
          all_association_attribute_prop TYPE string VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
          all_action_property            TYPE string VALUE 'ALL_ACTION_PROPERTY',
          all_action_attribute_property  TYPE string VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
          all_query_property             TYPE string VALUE 'ALL_QUERY_PROPERTY',
          all_query_attribute_property   TYPE string VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
          all_subtree_property           TYPE string VALUE 'ALL_SUBTREE_PROPERTY',
        END OF property,
      END OF ztt_i_task_comments,
      BEGIN OF ztt_i_task_time_log,
        BEGIN OF property,
          all_node_property              TYPE string VALUE 'ALL_NODE_PROPERTY',
          all_node_attribute_property    TYPE string VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
          all_association_property       TYPE string VALUE 'ALL_ASSOCIATION_PROPERTY',
          all_association_attribute_prop TYPE string VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
          all_action_property            TYPE string VALUE 'ALL_ACTION_PROPERTY',
          all_action_attribute_property  TYPE string VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
          all_query_property             TYPE string VALUE 'ALL_QUERY_PROPERTY',
          all_query_attribute_property   TYPE string VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
          all_subtree_property           TYPE string VALUE 'ALL_SUBTREE_PROPERTY',
        END OF property,
      END OF ztt_i_task_time_log,
      BEGIN OF ztt_i_task_transport_request,
        BEGIN OF property,
          all_node_property              TYPE string VALUE 'ALL_NODE_PROPERTY',
          all_node_attribute_property    TYPE string VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
          all_association_property       TYPE string VALUE 'ALL_ASSOCIATION_PROPERTY',
          all_association_attribute_prop TYPE string VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
          all_action_property            TYPE string VALUE 'ALL_ACTION_PROPERTY',
          all_action_attribute_property  TYPE string VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
          all_query_property             TYPE string VALUE 'ALL_QUERY_PROPERTY',
          all_query_attribute_property   TYPE string VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
          all_subtree_property           TYPE string VALUE 'ALL_SUBTREE_PROPERTY',
        END OF property,
      END OF ztt_i_task_transport_request,
    END OF sc_association_attribute .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">#GENERATED#</p>
    sc_bo_key  TYPE /bobf/obm_bo_key VALUE '0250E0674B721EEAAEF65901B030F3C9' .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">#GENERATED#</p>
    sc_bo_name TYPE /bobf/obm_name VALUE 'ZTT_I_TASKS' .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Determinations</p>
    BEGIN OF sc_determination,
      BEGIN OF ztt_i_tasks,
        action_and_field_control TYPE /bobf/det_key VALUE '0250E0674B721EEAAF8DC7727689FDD4',
        admin_data               TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF7920D8297B443',
        at_creation              TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF7920D82979443',
      END OF ztt_i_tasks,
      BEGIN OF ztt_i_task_comments,
        admin_data  TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF798B0BEC5B445',
        at_creation TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF798B0BEC59445',
      END OF ztt_i_task_comments,
      BEGIN OF ztt_i_task_time_log,
        admin_data  TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF79F492241F447',
        at_creation TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF79F492241D447',
        total_hours TYPE /bobf/det_key VALUE '0250E0674B721EEAAF8F8A5833DF7E95',
      END OF ztt_i_task_time_log,
      BEGIN OF ztt_i_task_transport_request,
        admin_data  TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF79F4922421447',
        at_creation TYPE /bobf/det_key VALUE '0250E0674B721EEAAEF79F4922423447',
      END OF ztt_i_task_transport_request,
    END OF sc_determination .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Groups</p>
    BEGIN OF sc_group,
      ztt_i_tasks TYPE /bobf/obm_group_key VALUE '0250E0674B721EEAAEF7A4B3D4EEB44C',
    END OF sc_group .
  CONSTANTS:
    sc_model_version TYPE /bobf/conf_version VALUE '00000' .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Nodes</p>
    BEGIN OF sc_node,
      ztt_i_tasks                    TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF65901B03133C9',
      ztt_i_tasks_lock               TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF65901B031B3C9',
      ztt_i_tasks_message            TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF65901B03173C9',
      ztt_i_tasks_property           TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF65901B03273C9',
      ztt_i_task_comments            TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF66F0E669B33D1',
      ztt_i_task_comments_message    TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF66F0E66A0D3D1',
      ztt_i_task_comments_property   TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF66F0E66A113D1',
      ztt_i_task_time_log            TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF6611C0E4B13CB',
      ztt_i_task_time_log_message    TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF6611C0E5173CB',
      ztt_i_task_time_log_property   TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF6611C0E51B3CB',
      ztt_i_task_transport_request   TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF67E42345953DA',
      ztt_i_task_transport_request_m TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF67E42345F53DA',
      ztt_i_task_transport_request_p TYPE /bobf/obm_node_key VALUE '0250E0674B721EEAAEF67E42345F93DA',
    END OF sc_node .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Node Attributes</p>
    BEGIN OF sc_node_attribute,
      BEGIN OF ztt_i_tasks,
        node_data              TYPE string VALUE 'NODE_DATA',
        project_code           TYPE string VALUE 'PROJECT_CODE',
        code                   TYPE string VALUE 'CODE',
        description            TYPE string VALUE 'DESCRIPTION',
        status                 TYPE string VALUE 'STATUS',
        estimation             TYPE string VALUE 'ESTIMATION',
        time_unit              TYPE string VALUE 'TIME_UNIT',
        ended_on               TYPE string VALUE 'ENDED_ON',
        functional_responsible TYPE string VALUE 'FUNCTIONAL_RESPONSIBLE',
        technical_responsible  TYPE string VALUE 'TECHNICAL_RESPONSIBLE',
        admin_data             TYPE string VALUE 'ADMIN_DATA',
        crea_date_time         TYPE string VALUE 'CREA_DATE_TIME',
        crea_uname             TYPE string VALUE 'CREA_UNAME',
        lchg_date_time         TYPE string VALUE 'LCHG_DATE_TIME',
        lchg_uname             TYPE string VALUE 'LCHG_UNAME',
      END OF ztt_i_tasks,
      BEGIN OF ztt_i_task_comments,
        node_data      TYPE string VALUE 'NODE_DATA',
        project_code   TYPE string VALUE 'PROJECT_CODE',
        task_code      TYPE string VALUE 'TASK_CODE',
        code           TYPE string VALUE 'CODE',
        commentary     TYPE string VALUE 'COMMENTARY',
        admin_data     TYPE string VALUE 'ADMIN_DATA',
        crea_date_time TYPE string VALUE 'CREA_DATE_TIME',
        crea_uname     TYPE string VALUE 'CREA_UNAME',
        lchg_date_time TYPE string VALUE 'LCHG_DATE_TIME',
        lchg_uname     TYPE string VALUE 'LCHG_UNAME',
      END OF ztt_i_task_comments,
      BEGIN OF ztt_i_task_time_log,
        node_data      TYPE string VALUE 'NODE_DATA',
        project_code   TYPE string VALUE 'PROJECT_CODE',
        task_code      TYPE string VALUE 'TASK_CODE',
        code           TYPE string VALUE 'CODE',
        start_ts       TYPE string VALUE 'START_TS',
        end_ts         TYPE string VALUE 'END_TS',
        total_hours    TYPE string VALUE 'TOTAL_HOURS',
        admin_data     TYPE string VALUE 'ADMIN_DATA',
        crea_date_time TYPE string VALUE 'CREA_DATE_TIME',
        crea_uname     TYPE string VALUE 'CREA_UNAME',
        lchg_date_time TYPE string VALUE 'LCHG_DATE_TIME',
        lchg_uname     TYPE string VALUE 'LCHG_UNAME',
      END OF ztt_i_task_time_log,
      BEGIN OF ztt_i_task_transport_request,
        node_data         TYPE string VALUE 'NODE_DATA',
        project_code      TYPE string VALUE 'PROJECT_CODE',
        task_code         TYPE string VALUE 'TASK_CODE',
        transport_request TYPE string VALUE 'TRANSPORT_REQUEST',
        commentary        TYPE string VALUE 'COMMENTARY',
        admin_data        TYPE string VALUE 'ADMIN_DATA',
        crea_date_time    TYPE string VALUE 'CREA_DATE_TIME',
        crea_uname        TYPE string VALUE 'CREA_UNAME',
        lchg_date_time    TYPE string VALUE 'LCHG_DATE_TIME',
        lchg_uname        TYPE string VALUE 'LCHG_UNAME',
      END OF ztt_i_task_transport_request,
    END OF sc_node_attribute .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Node Categories</p>
    BEGIN OF sc_node_category,
      BEGIN OF ztt_i_tasks,
        root TYPE /bobf/obm_node_cat_key VALUE '0250E0674B721EEAAEF65901B03153C9',
      END OF ztt_i_tasks,
      BEGIN OF ztt_i_task_comments,
        ztt_i_task_comments TYPE /bobf/obm_node_cat_key VALUE '0250E0674B721EEAAEF66F0E66A073D1',
      END OF ztt_i_task_comments,
      BEGIN OF ztt_i_task_time_log,
        ztt_i_task_time_log TYPE /bobf/obm_node_cat_key VALUE '0250E0674B721EEAAEF6611C0E5113CB',
      END OF ztt_i_task_time_log,
      BEGIN OF ztt_i_task_transport_request,
        ztt_i_task_transport_request TYPE /bobf/obm_node_cat_key VALUE '0250E0674B721EEAAEF67E42345EF3DA',
      END OF ztt_i_task_transport_request,
    END OF sc_node_category .
  CONSTANTS:
    "! <p class="shorttext synchronized" lang="en">Validations</p>
    BEGIN OF sc_validation,
      BEGIN OF ztt_i_tasks,
        project_code TYPE /bobf/val_key VALUE '0250E0674B721EEAAEF7A4B3D4EE544C',
      END OF ztt_i_tasks,
    END OF sc_validation .
ENDINTERFACE.
